### ISSUE TITLE
Cant get working on Android

### ISSUE THREAD

**Issue by compains** [lelandrichardson/react-native-maps#164]
Hi 

I managed to get it working on iOs, but in android is failing, on real device and emulator.

This is the error message that I receive on the Android Studio 
```

04-04 13:25:30.410 2564-2564/com.app******* E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.app*******, PID: 2564
                                                                 java.lang.NoSuchMethodError: No static method zzy(Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzx; or its super classes (declaration of 'com.google.android.gms.common.internal.zzx' appears in /data/app/com.app*******-2/base.apk)
                                                                     at com.google.android.gms.measurement.internal.zzt.zzaU(Unknown Source)
                                                                     at com.google.android.gms.measurement.AppMeasurementContentProvider.onCreate(Unknown Source)
                                                                     at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
                                                                     at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
                                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:5153)
                                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748)
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688)
                                                                     at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

The app is built correctly but when I try to launch it a get a "Application has stopped" alert.

Any idea?

Thanks in advance!!

**Comment by jrichardlai** [comment]
Can you check your version of com.google.android.gms:play-services-base in your app? react-native-maps using 8.4.0, I noticed there might be conflicts in versions.

**Comment by compains** [comment]
Hi @jrichardlai thanks for your answer. I don't have any Java (neither Android) environment experience.

Where can I check the com.google.android.gms:play-services-base version un my app, I found the file inside react-native-maps module that specifies the 8.4.0 version, but i can't find anything similar in my app.

**Comment by compains** [comment]
Hi @jrichardlai I managed to make the app fire up. I added these lines

`compile "com.google.android.gms:play-services-base:8.4.0"
    compile 'com.google.android.gms:play-services-maps:8.4.0'`

to the build.gradle (the onen from the app folder) and the i found that the react-native-push-notificacion uses 8.3.0, so I changed the dependency to 8.4.0 (I have no idea of what I'm doing....) and the app fires up. Unfortunately the map area appears empty and a warning message appears saying 

> Native component for "RCTMap" does not exist

Any help is welcome. Thaks!!

**Comment by compains** [comment]
@jrichardlai After some issues with my wifi, I was able to run the app on a device (an old Galaxy S2) and the map is working. If I left the react-native-push-notification build.gradle file as it was originally 
`compile 'com.google.android.gms:play-services-gcm:8.3.0'`

As said before, I have no experience in Java or Android environments so if there is a better way of solving this issue....

Thanks!!

**Comment by compains** [comment]
Forking the repos and fixing Google Play Api versions make it works. Closing

**Comment by mauron85** [comment]
Hmm, i've same problem. I don't use any other plugin that uses google play services. 
Device: Nexus 4
OS: CM 13 (Android M)
Plugin version: 0.7.1
React-native version: 0.29.0

```
08-14 20:34:01.962 12164 12164 E AndroidRuntime: java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzx; or its super classes (declaration of 'com.google.android.gms.common.internal.zzx' appears in /data/app/com.marianhello.RNBGExample-1/base.apk)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:59)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:27)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:206)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:874)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:847)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:125)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at android.view.Choreographer.doFrame(Choreographer.java:603)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at android.os.Handler.handleCallback(Handler.java:739)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at android.os.Handler.dispatchMessage(Handler.java:95)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at android.os.Looper.loop(Looper.java:148)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at android.app.ActivityThread.main(ActivityThread.java:5466)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at java.lang.reflect.Method.invoke(Native Method)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-14 20:34:01.962 12164 12164 E AndroidRuntime:       	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-14 20:34:01.964   661  3059 W ActivityManager:   Force finishing activity com.marianhello.RNBGExample/.MainActivity
```

**Comment by cubbuk** [comment]
I was having the same error as the dependencies of my app are relying on the latest version. So from android studio I had to change version google play services dependencies to same one I was using. Thats not very useful solution as literally I had to change files under node_modules, but solved the problem for a short solution.

**Comment by iiitmahesh** [comment]
Ref
 #452 
My problem was solved with following code in **android/app/build.gradle**
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

```
    compile project(':react-native-maps')    
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile "com.google.android.gms:play-services-base:+"
    compile "com.google.android.gms:play-services-maps:+"
```
