### ISSUE TITLE
unable to run example

### ISSUE THREAD

**Issue by warmwater** [lelandrichardson/react-native-maps#217]
on OS X v10.11.4

node v6.0.0
npm 3.8.6
react-native-cli 0.2.0
xcode 7.3.1

$ git clone https://github.com/lelandrichardson/react-native-maps
$ cd react-native-maps
$ npm install
$ react-native run-ios

```
Found Xcode project AirMaps.xcodeproj
Launching iPhone 6 (9.3)...
Building using "xcodebuild -project AirMaps.xcodeproj -scheme AirMaps -destination id=43F9E5B5-9A4F-451E-8CB8-0EFDF2EC80F5 -derivedDataPath build"
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/bigdav/Projects/react-native-maps/ios/build

xcodebuild: error: The project named "AirMaps" does not contain a scheme named "AirMaps". The "-list" option can be used to find the names of the schemes in the project.
Installing build/Build/Products/Debug-iphonesimulator/AirMaps.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/bigdav/Projects/react-native-maps/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/AirMaps.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:470:13)
    at Object.execFileSync (child_process.js:490:13)
    at _runIOS (runIOS.js:91:34)
    at runIOS.js:24:5
    at tryCallTwo (/Users/bigdav/Projects/react-native-maps/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/bigdav/Projects/react-native-maps/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/bigdav/Projects/react-native-maps/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (runIOS.js:23:10)
    at Object.run (/Users/bigdav/Projects/react-native-maps/node_modules/react-native/local-cli/cli.js:87:13)
    at Object.<anonymous> (/Users/bigdav/.nvm/versions/node/v6.0.0/lib/node_modules/react-native-cli/index.js:88:7)
```

$ lsof -n -i4TCP:8081, not occupied

**Comment by ivanfoong** [comment]
@warmwater did you try `react-native run-ios` in the `example` folder?

**Comment by warmwater** [comment]
ah i didn't enter "example" folder before npm install and run-ios

thanks for help
