### ISSUE TITLE
Installation Failed on react-native@0.28.0

### ISSUE THREAD

**Issue by sarovin** [lelandrichardson/react-native-maps#426]
Hi,
i have follow your installation doc:

```
npm install react-native-maps --save
rnpm link
```

and after i set api key.

But i have this error with "react-native run-ios":

```
 ** BUILD FAILED **

The following build commands failed:
	CompileC /Users/saro/Projects/openshift/FoodAZoneApp/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapCallout.o AirMaps/AIRMapCallout.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

and this error with "react-native run-android":

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-maps : Configuration with name 'default' not found.
```

Any suggestion?

**Comment by linda90321** [comment]
I was having same issue. Any solution?

**Comment by linda90321** [comment]
#371 (comment)

**Comment by sarovin** [comment]
@linda90321 
i must update to react-native@0.30 and follow this #411 .

After you must set  settings.gradle like this:

```
include ':react-native-maps:lib'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/android/lib')
```

But i have another problem when start app:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp/com.myapp.MainActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java)
```

**Comment by perkola** [comment]
Having the same problem. React Native `v.0.30.0`, React Native Maps `v.0.7,1` using a blank project and following the [https://github.com/lelandrichardson/react-native-maps/blob/master/docs/installation.md#android](instructions).

**Comment by sarovin** [comment]
yes, it fix.

**Comment by perkola** [comment]
@sarovin no this just produces another error for me.

**Comment by sarovin** [comment]
@perkola 
Remove node_modules, ios and android  folders. 
Repeat instructions.

**Comment by gferreyra91** [comment]
@perkola can you fix the problem?

**Comment by perkola** [comment]
@gferreyra91 what fixed it for me was creating a new project and copying over my edited code.
