### ISSUE TITLE
RN 0.32 / Android - App crashes when rendering MapView

### ISSUE THREAD

**Issue by FuzzyTree** [lelandrichardson/react-native-maps#506]
Whenever I try to render a `MapView` component, the app briefly displays the map grid with the Google logo in the bottom left corner and crashes with the following error

```
08-28 21:18:34.679 26984 26984 E AndroidRuntime: FATAL EXCEPTION: main
08-28 21:18:34.679 26984 26984 E AndroidRuntime: Process: com.aw, PID: 26984
08-28 21:18:34.679 26984 26984 E AndroidRuntime: java.lang.NoSuchMethodError: No direct method <init>(IJ)V in class Lcom/facebook/react/uimanager/events/Event; or its super classes (declaration of 'com.facebook.react.uimanager.events.Event' appears in /data/app/com.aw-2/base.apk)
08-28 21:18:34.679 26984 26984 E AndroidRuntime:        at com.airbnb.android.react.maps.RegionChangeEvent.<init>(RegionChangeEvent.java:16)
08-28 21:18:34.679 26984 26984 E AndroidRuntime:        at com.airbnb.android.react.maps.AirMapView$8.onCameraChange(AirMapView.java:220)
08-28 21:18:34.679 26984 26984 E AndroidRuntime:        at com.google.android.gms.maps.GoogleMap$12.onCameraChange(Unknown Source)
08-28 21:18:34.679 26984 26984 E AndroidRuntime:        at com.google.android.gms.maps.internal.zze$zza.onTransact(Unknown Source)
08-28 21:18:34.679 26984 26984 E AndroidRuntime:        at android.os.Binder.transact(Binder.java:387)
08-28 21:18:34.679 26984 26984 E AndroidRuntime:        at wg.a(:com.google.android.gms.DynamiteModulesB:93)
08-28 21:18:34.679 26984 26984 E AndroidRuntime:        at maps.D.a.a(Unknown Source)
08-28 21:18:34.679 26984 26984 E AndroidRuntime:        at maps.D.a$1.run(Unknown Source)
08-28 21:18:34.679 26984 26984 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
08-28 21:18:34.679 26984 26984 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
08-28 21:18:34.679 26984 26984 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:158)
08-28 21:18:34.679 26984 26984 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7229)
08-28 21:18:34.679 26984 26984 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-28 21:18:34.679 26984 26984 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
08-28 21:18:34.679 26984 26984 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

This happens from a fresh app created with `react-init` and `react-native-maps` as the only added plugin and following the instructions at https://github.com/lelandrichardson/react-native-maps/blob/master/docs/installation.md

If I only import `MapView` without using the component in `render`, then the app doesn't crash but I get the following error in the debugger multiple times

```
index.android.bundle:24138Warning: ReactClass: You're attempting to include a mixin that is either null or not an object. Check the mixins included by the component, as well as any mixins they include themselves. Expected object but got undefined.
```

index.android.js

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

import MapView from 'react-native-maps';

class aw extends Component {
  render() {
    return (
        <View style={ styles.container }>
            <MapView
                style={ styles.map }
                initialRegion={{
                  latitude: 37.78825,
                  longitude: -122.4324,
                  latitudeDelta: 0.0922,
                  longitudeDelta: 0.0421,
                }}
            />
        </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
});

AppRegistry.registerComponent('aw', () => aw);
```

**Comment by FuzzyTree** [comment]
Duplicate of https://github.com/lelandrichardson/react-native-maps/pull/502
