### ISSUE TITLE
0.8.0 crash android - NoSuchMethodError AirMapView$8.onCameraChange...

### ISSUE THREAD

**Issue by npomfret** [lelandrichardson/react-native-maps#514]
My app is crashing with RN 0.32 and react-native-maps 0.8.0:

```
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.pomochat, PID: 18967
java.lang.NoSuchMethodError: No direct method <init>(IJ)V in class Lcom/facebook/react/uimanager/events/Event; or its super classes (declaration of 'com.facebook.react.uimanager.events.Event' appears in /data/data/com.pomochat/files/instant-run/dex/slice-com.facebook.react-react-native-0.32.0_298e83093ee0198f7421beb42bd42f378fb6cc2d-classes.dex)
at com.airbnb.android.react.maps.RegionChangeEvent.<init>(RegionChangeEvent.java:16)
at com.airbnb.android.react.maps.AirMapView$8.onCameraChange(AirMapView.java:220)
at com.google.android.gms.maps.GoogleMap$12.onCameraChange(Unknown Source)
at com.google.android.gms.maps.internal.zze$zza.onTransact(Unknown Source)
at android.os.Binder.transact(Binder.java:385)
at wg.a(:com.google.android.gms.DynamiteModulesB:93)
at maps.D.a.a(Unknown Source)
at maps.D.a$1.run(Unknown Source)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5631)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
```

I've looked at the Event class in react-native and it does have that contractor.  Quite confused.

**Comment by npomfret** [comment]
Oh, I see its being discussed elsewhere https://github.com/lelandrichardson/react-native-maps/pull/502
