### ISSUE TITLE
[Blocker] Android build

### ISSUE THREAD

**Issue by kitolog** [lelandrichardson/react-native-maps#560]
Hi all, 
I'm using the latest version of react-native-maps lib (0.8.2) and couldn't build my android.
What I did:
I reinstalled react native maps, made ./gradlew clean, deleted build directory and then run react-native run-android with no result. All times I see only this error message.

```
projectResult compacted from 4451,1KiB to 2874,5KiB to save 1576,6KiB
Merged dex A (2567 defs/3191,6KiB) with dex B (128 defs/284,8KiB). Result is 2695 defs/2874,5KiB. Took 0,3s
Merged dex A (2695 defs/2874,5KiB) with dex B (193 defs/310,2KiB). Result is 2888 defs/3896,4KiB. Took 0,2s

14:22:36.634 [ERROR] [org.gradle.api.Project] Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/MessengerCompat$1;
Unknown source file : 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file : 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file : 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file : 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)

14:22:36.646 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':app:dexDebug'
14:22:36.647 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :app:dexDebug FAILED
14:22:36.654 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :app:dexDebug (Thread[main,5,main]) completed. Took 4.853 secs.
14:22:36.655 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 12.199 secs, idle: 0.167 secs
14:22:36.709 [ERROR] [org.gradle.BuildExceptionReporter] 
14:22:36.710 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
14:22:36.710 [ERROR] [org.gradle.BuildExceptionReporter] 
14:22:36.711 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
14:22:36.711 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':app:dexDebug'.
14:22:36.711 [ERROR] [org.gradle.BuildExceptionReporter] > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
14:22:36.712 [ERROR] [org.gradle.BuildExceptionReporter] 
14:22:36.713 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
14:22:36.713 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
14:22:36.719 [LIFECYCLE] [org.gradle.BuildResultLogger] 
14:22:36.720 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
14:22:36.721 [LIFECYCLE] [org.gradle.BuildResultLogger] 
14:22:36.722 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 41.72 secs
14:22:36.814 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Plugin Resolution Cache (/Users/kitolog/.gradle/caches/2.2/plugin-resolution) was closed 0 times.
```

**Comment by btoueg** [comment]
I'm using the latest version myself with no build issue. I don't see anything related to `react-native-maps` in your build.

Have you tried completely removing `react-native-maps` and check if it still builds?

**Comment by kitolog** [comment]
Arrgh!!!!!
I solve it. react-native-push-notification lib also using play services and tries to inject both maps and notifications dependencies. Thank you! After removing push notifications, build works.
